spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:39691/testdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1

  rabbitmq:
    listener:
      simple:
        prefetch: 5
        max-concurrency: 20
        concurrency: 10
        ##不重新入队列(入队列的配置也要设置为false)
        default-requeue-rejected: false
        retry:
          ##开启消费者自动重试
          enabled: true
          max-attempts: 3
        ##自动签收,会尝试n次后，如果还丢失就会抛弃
        acknowledge-mode: manual
    host: 139.9.0.236
    port: 5673
    virtual-host: dev
    username: corn
    password: corn#9527

  redis:
    host: 127.0.0.1
    password:

server:
  port: 13000

me:
  name: su
  age: 18