
spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: db0
      db0:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
    sharding:
      tables:
        user:
          actual-data-nodes: db0.user_0,db0.user_1
          table-strategy:
            inline:
              sharding-column: age
              algorithm-expression: user_$->{age%2}
          keyGenerator:
            type: SNOWFLAKE
            column: id

  rabbitmq:
    listener:
      simple:
        prefetch: 5
        max-concurrency: 20
        concurrency: 10
        ##不重新入队列(入队列的配置也要设置为false)
        default-requeue-rejected: false
        retry:
          ##开启消费者自动重试
          enabled: true
          max-attempts: 3
        ##自动签收,会尝试n次后，如果还丢失就会抛弃
        acknowledge-mode: manual
    host: 139.9.0.236
    port: 5673
    virtual-host: dev
    username: corn
    password: corn#9527

  redis:
    host: 127.0.0.1
    password:
    port: 6379

server:
  port: 13000
  tomcat:
    ##等待队列
    accept-count: 1
    ##tcp最大连接数
    max-connections: 2
    ##核心线程数
    threads:
      max: 2

me:
  name: su
  age: 18